org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0
maven_group = com.konstasiil.totemskin
archives_base_name = totemskin

# Dependencies
minecraft_version = 26.1.2
yarn_mappings = 26.1.2+build.1
loader_version = 0.15.11

# Fabric API version
fabric_version = 0.92.0+1.20.1

# Config libraries
cloth_config_version = 26.1.154
modmenu_version = 18.0.0-alpha.8
